### ISSUE TITLE
Does Patito rely on subclasses of Polars `DataFrame`s  preserving their type after method calls?

### ISSUE THREAD

**Issue by stinodego** [kolonialno/patito#60]
Hi, I'm a Polars developer! Quick question to the maintainers of this library:

**Does Patito rely on subclasses of Polars `DataFrame`s  preserving their type after method calls?**

### Context

We are currently employing some 'tricks' to preserve subclasses on our main types (`Series` and `DataFrame`). For example, this is the implementation of `DataFrame.select`:

```python
def select(self, exprs, *more_exprs, **named_exprs):
    return self._from_pydf(
        self.lazy()
        .select(exprs, *more_exprs, **named_exprs)
        .collect(no_optimization=True)
        ._df
    )
```

Note we are dispatching to the lazy implementation by calling `.lazy()` first and then `.collect()` afterwards. This yields a generic dataframe, which we 'wrap' by calling `self._from_pydf` to preserve the subclass of the original DataFrame.

We would like to get rid of that last step, for a few reasons:
* Reduce function call overhead
* Improve code readability
* The 'feature' is unreliable (some methods support it, others don't)
* We do not view this feature as a viable method of achieving interoperability in a broader sense

We have identified as Patito as an important dependent that might rely on this functionality, which is why I am checking here. Would be happy to hear from you!

**Comment by stinodego** [comment]
Tagging @JakobGM for visibility, as I see this repo has not been very active in the past months.

**Comment by ion-elgreco** [comment]
@stinodego further development of patito has been moved to https://github.com/JakobGM/patito

**Comment by stinodego** [comment]
Thanks @ion-elgreco , I guess this can be closed as we have decided to go ahead and drop subclassing support.
